// Javascript Dispatch Events.
// https://www.javascripttutorial.net/javascript-dom/javascript-dispatchevent/

// Javascript dispatch Event 

// How to programmatically create and dispatch events using event constructor dispatchEvent() method.

// typically, events are generated by user actions, such as mouse clicks and keypresses, in additon events can be generated from the code.

// generate an event programmatically
// create a new event object using event constructor.
// then trigger the event using element.dispatchEvent() method.

// event constructor.
// let event = new Event(type, [,options]);

// event constructer accepts two parameters
// type and options 
// type is a string that specifies event type such as click.
// option is an object with two optional properties,
// bubble and cancelable are boolean values 

// dispatchEvent() method.
// after creating an event you can fire it on a target element using dispatchEvent() method.
// Element.dispatchEvent(event);

// js code for dispatchEvent().
const btn = document.querySelector('#btn');
btn.addEventListener('click', function() {
    alert('Mouse Clicked!!!!');
});

const clickedEvent = new event('click');
btn.dispatchEvent(clickedEvent);
